apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainwave-react
  labels:
    app: brainwave-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainwave-react
  template:
    metadata:
      labels:
        app: brainwave-react
    spec:
      containers:
      - name: brainwave-react
        image: REPLACE_WITH_IMAGE
        ports:
        - containerPort: 80
