apiVersion: v1
kind: Service
metadata:
  name: brainwave-react-svc
spec:
  selector:
    app: brainwave-react
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
